{{-- resources/views/admin/reports/academic-pdf.blade.php --}}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Academic Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header h1 {
            color: #2c3e50;
        }

        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        .info-table th,
        .info-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .info-table th {
            background-color: #f2f2f2;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Academic Report</h1>
        <p>Generated on: {{ date('F d, Y') }}</p>
    </div>

    <table class="info-table">
        <tr>
            <th>Student Name</th>
            <td>{{ $student->full_name ?? 'N/A' }}</td>
            <th>Class</th>
            <td>{{ $student->class->name ?? 'N/A' }}</td>
        </tr>
        <tr>
            <th>Section</th>
            <td>{{ $student->section->name ?? 'N/A' }}</td>
            <th>Roll Number</th>
            <td>{{ $student->roll_number ?? 'N/A' }}</td>
        </tr>
        <tr>
            <th>Academic Year</th>
            <td>{{ $student->academic_year ?? date('Y') }}</td>
            <th>Admission Date</th>
            <td>{{ $student->admission_date->format('d-m-Y') ?? 'N/A' }}</td>
        </tr>
    </table>

    @if (isset($marks) && count($marks) > 0)
        <h3>Academic Performance</h3>
        <table class="info-table">
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Marks Obtained</th>
                    <th>Total Marks</th>
                    <th>Percentage</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($marks as $mark)
                    <tr>
                        <td>{{ $mark->subject->name ?? 'N/A' }}</td>
                        <td>{{ $mark->marks_obtained }}</td>
                        <td>{{ $mark->total_marks }}</td>
                        <td>{{ number_format(($mark->marks_obtained / $mark->total_marks) * 100, 2) }}%</td>
                        <td>{{ $mark->grade }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>Generated by Student Management System</p>
        <p>Page {{ $page }} of {!! $pageCount !!}</p>
    </div>
</body>

</html>
